### PR TITLE
Unbalanced Window

### PR DESCRIPTION
**Pull request by Strilanc**
This is a very important change.

### CODE REVIEW

**Comment by Strilanc** [comment]
The overall PR status shouldn't be pinned yellow by the merge waiting for approval.

The status page should probably let me see a submit queue.

Status page 'Back to PR' goes nowhere.

@quantum-merge-bot dance

**Comment by kunalq** [comment]
@Strilanc Using the Merge commit status to gate merging means only the merge bot can do the merging, but it also gives us a consistent place with the "latest" information.

Hm, yeah, the Back to PR page is bugged. I'll work on that in a bit.

**Review by kunalq — APPROVED** [review]

**Comment by kunalq** [comment]
@quantum-merge-bot status success

**Comment by Strilanc** [comment]
Mmmmmm, I love race conditions in the morning.

**Comment by Strilanc** [comment]
@quantum-merge-bot status success

**Pull request merged**
